// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKKNzrGtvtdvjovUNUpnPQ238gxC4A2Uw',
    appId: '1:367335273390:web:525d120b1d5e41621f0e3f',
    messagingSenderId: '367335273390',
    projectId: 'pizza-app-258',
    authDomain: 'pizza-app-258.firebaseapp.com',
    storageBucket: 'pizza-app-258.appspot.com',
    measurementId: 'G-1J8KMGTEF2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7waxGSsnwn6MiqyVHCPDZIIMvWE7u0oc',
    appId: '1:367335273390:android:418e300224cf7c9b1f0e3f',
    messagingSenderId: '367335273390',
    projectId: 'pizza-app-258',
    storageBucket: 'pizza-app-258.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMSXzSrA9suf_StNSu7rL-XPH3fbnmdJ4',
    appId: '1:367335273390:ios:4b0a37eaef0f67dc1f0e3f',
    messagingSenderId: '367335273390',
    projectId: 'pizza-app-258',
    storageBucket: 'pizza-app-258.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMSXzSrA9suf_StNSu7rL-XPH3fbnmdJ4',
    appId: '1:367335273390:ios:4b0a37eaef0f67dc1f0e3f',
    messagingSenderId: '367335273390',
    projectId: 'pizza-app-258',
    storageBucket: 'pizza-app-258.appspot.com',
    iosBundleId: 'com.example.pizzaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKKNzrGtvtdvjovUNUpnPQ238gxC4A2Uw',
    appId: '1:367335273390:web:71744ba6196009721f0e3f',
    messagingSenderId: '367335273390',
    projectId: 'pizza-app-258',
    authDomain: 'pizza-app-258.firebaseapp.com',
    storageBucket: 'pizza-app-258.appspot.com',
    measurementId: 'G-4CVS4N2DGL',
  );
}
